################################################################################
# General

# Improve colors
set -g default-terminal 'screen-256color'

# mouse support
set-option -g mouse on

# vim bindings
set -g mode-keys vi

# secondary prefix
set -g prefix2 C-space

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

################################################################################
# Plugins

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'

# tinted-theming/tinted-tmux
set -g @plugin 'tinted-theming/tinted-tmux'
set -g @tinted-color "base16-$BASE16_THEME"

# tmux-plugins/tmux-continuum
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'kitty'
set -g @continuum-restore 'on'

set-option -g status "on"
set-option -g status-justify "left" 
#set-option -g status-left "#[fg=#$BASE16_COLOR_05_HEX,bg=#$BASE16_COLOR_03_HEX] #S #[fg=#$BASE16_COLOR_03_HEX,bg=#$BASE16_COLOR_01_HEX,nobold,noitalics,nounderscore]"
set-option -g status-left "#[fg=#$BASE16_COLOR_05_HEX,bg=#$BASE16_COLOR_03_HEX] #S #[fg=#$BASE16_COLOR_03_HEX,bg=#$BASE16_COLOR_0A_HEX,nobold,noitalics,nounderscore]"
set-option -g status-left-length "80"
set-option -g status-left-style none
# set-option -g status-right "#[fg=#$BASE16_COLOR_02_HEX,bg=#$BASE16_COLOR_01_HEX nobold, nounderscore, noitalics]#[fg=#$BASE16_COLOR_04_HEX,bg=#$BASE16_COLOR_02_HEX] %Y-%m-%d  %H:%M #[fg=#$BASE16_COLOR_05_HEX,bg=#$BASE16_COLOR_02_HEX,nobold,noitalics,nounderscore]#[fg=#$BASE16_COLOR_01_HEX,bg=#$BASE16_COLOR_05_HEX] #h "
# set-option -g status-right-length "80"
# set-option -g status-right-style none
# set-window-option -g window-status-current-format "#[fg=#$BASE16_COLOR_01_HEX,bg=#$BASE16_COLOR_0A_HEX,nobold,noitalics,nounderscore]#[fg=#$BASE16_COLOR_02_HEX,bg=#$BASE16_COLOR_0A_HEX] #I #[fg=#$BASE16_COLOR_02_HEX,bg=#$BASE16_COLOR_0A_HEX,bold] #W #[fg=#$BASE16_COLOR_0A_HEX,bg=#$BASE16_COLOR_01_HEX,nobold,noitalics,nounderscore]"
set-window-option -g window-status-current-format "#[fg=#$BASE16_COLOR_02_HEX,bg=#$BASE16_COLOR_0A_HEX] #I #[fg=#$BASE16_COLOR_02_HEX,bg=#$BASE16_COLOR_0A_HEX,bold] #W #[fg=#$BASE16_COLOR_0A_HEX,bg=#$BASE16_COLOR_01_HEX,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[fg=#$BASE16_COLOR_01_HEX,bg=#$BASE16_COLOR_02_HEX,noitalics]#[fg=#$BASE16_COLOR_06_HEX,bg=#$BASE16_COLOR_02_HEX] #I #[fg=#$BASE16_COLOR_06_HEX,bg=#$BASE16_COLOR_02_HEX] #W #[fg=#$BASE16_COLOR_02_HEX,bg=#$BASE16_COLOR_01_HEX,noitalics]"
set-window-option -g window-status-separator ""

################################################################################
# TPM (must be last)
set -g @plugin 'tmux-plugins/tpm'
run ~/.tmux/plugins/tpm/tpm

