shell = "zsh -c '{}'"
default-scheme = "base16-catppuccin-machiato"

[[items]]
name = "base16-shell"
path = "https://github.com/tinted-theming/base16-shell"
themes-dir = "scripts"
hook = "source %f"
supported-systems = ["base16"]

[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
hook = "tmux run 2> /dev/null && tmux source-file %f"
themes-dir = "colors"
